name: movie_scope
description: A flutter application for exploring the practice of clean architecture and TDD alongside flutter framework
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.0
  # Value equality
  equatable: ^1.2.6
  # Functional programming Either type
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  mockito: ^4.1.3

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
